version: '3.1'

services:
  app-frontend:
    container_name: app-frontend
    build: app_frontend
    restart: always
    tty: true
    ports:
      - 8001:80
    logging:
      options:
        max-size: "100m"
        max-file: "100"
    env_file:
      - ./.env_web_app
    networks:
      - web

networks:
  web:
    external: true #needs to be created by other file
    name: shared-web
